### ISSUE TITLE
Line 834 of recurrent.py

### ISSUE THREAD

**Issue by sxjscience** [skaae/nntools#2]
The current version is
834: return [cell_fwd, cell_bck, hid_bck, hid_fwd]
Should be 
834: return [cell_fwd, cell_bck, hid_fwd, hid_bck] 
?

**Comment by skaae** [comment]
yes.

**Comment by skaae** [comment]
Do you want to pr or should i fix it?

**Comment by skaae** [comment]
I fixed it. Thanks
